services:
  nginx-server:
    image: nginx:1.27.4-alpine
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/certs:/etc/ca-certificates
      - /etc/letsencrypt/live/www.metaspaces.shop/fullchain.pem:/etc/ca-certificates/fullchain.pem
      - /etc/letsencrypt/live/www.metaspaces.shop/privkey.pem:/etc/ca-certificates/privkey.pem
    networks:
      - metamong-net
    depends_on:
      was-container-blue:
        condition: service_healthy

  # certbot:
  #   image: certbot/certbot
  #   command: certonly --webroot -w /usr/share/nginx/html -d www.metaspaces.shop
  #   volumes:
  #     - ./nginx/ngin
    
  was-container-blue:
    profiles:
      - blue
    image: hansoo0614/metamong-backend:latest
    container_name: backend-blue
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - CLIENT_DOMAIN=${CLIENT_DOMAIN}
      - CLIENT_ORIGIN=${CLIENT_ORIGIN}
      - JDBC_PASSWORD=${JDBC_PASSWORD}
      - JDBC_USERNAME=${JDBC_USERNAME}
      - JDBC_URL=${JDBC_URL}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - REDIS_HOST=${REDIS_HOST}
    networks:
      - metamong-net
    healthcheck:
      test: ["CMD", "curl", "-X", "HEAD", "-i", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 30s
      retries: 10
      start_period: 30s
    depends_on:
      redis:
        condition: service_started

  # was-container-green:
  #   profiles:
  #     - green
  #   image: hansoo0614/metamong-backend:latest
  #   container_name: backend-blue
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=prod
  #     - CLIENT_DOMAIN=${CLIENT_DOMAIN}
  #     - CLIENT_ORIGIN=${CLIENT_ORIGIN}
  #     - JDBC_PASSWORD=${JDBC_PASSWORD}
  #     - JDBC_USERNAME=${JDBC_USERNAME}
  #     - MAIL_HOST=${MAIL_HOST}
  #     - MAIL_PASSWORD=${MAIL_PASSWORD}
  #     - MAIL_USERNAME=${MAIL_USERNAME}
  #   networks:
  #     - metamong-net
  #   healthcheck:
  #     test: ["CMD", "curl", "-X", "HEAD", "-i", "http://localhost:8080/actuator/health"]
  #     interval: 1m30s
  #     timeout: 30s
  #     retries: 5
  #     start_period: 30s
  
  redis:
    container_name: redis-container
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - metamong-net

networks:
  metamong-net:
    driver: bridge
